name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # ルートをアップロードする（静的サイトの場合はそのままでOK）
          path: ./

  deploy:
    needs: upload-artifact
    runs-on: ubuntu-latest
    permissions:
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
